export enum WidgetTypeEnum {
  Link = 'link',
  Text = 'text',
  Image = 'image',
  Video = 'video',
  Blog = 'blog',
  Contact = 'contact',
  Carousel = 'carousel',
  Map = 'map',
  Webinar = 'webinar',
  Schedule = 'schedule',
  Social = 'social',
  Banner = 'banner',
  Profile = 'profile',
}
